using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;
using TMPro;
#if ENABLE_INPUT_SYSTEM
using UnityEngine.InputSystem;
#endif

/// <summary>
/// Singleton UI panel for displaying Information Items.
/// Features a centered sprite image and a "Click anywhere blank to close" background.
/// Disables player interaction & movement while open to prevent double interactions.
/// </summary>
public class InfoPanelUI : MonoBehaviour
{
    private static InfoPanelUI _instance;

    public static InfoPanelUI Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindFirstObjectByType<InfoPanelUI>(FindObjectsInactive.Include);
                if (_instance == null)
                {
                    GameObject managerObj = new GameObject("[InfoPanelUI]");
                    _instance = managerObj.AddComponent<InfoPanelUI>();
                }
            }
            return _instance;
        }
        private set => _instance = value;
    }

    [Header("UI References")]
    [Tooltip("The main container GameObject for the info panel.")]
    [SerializeField] private GameObject panel;

    [Tooltip("The UI Image in the center of the screen that displays the info graphic.")]
    [SerializeField] private Image contentImage;

    [Tooltip("The full-screen background overlay Image/Button used for click-outside-to-close.")]
    [SerializeField] private Button backgroundButton;

    public bool IsPanelActive => panel != null && panel.activeSelf;

    private int openedFrame = -1;
    private bool isAutoGenerated = false;
    private string pendingNotificationOnClose = null;

    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
    private static void AutoInitialize()
    {
        if (_instance == null)
        {
            _instance = FindFirstObjectByType<InfoPanelUI>(FindObjectsInactive.Include);
            if (_instance == null)
            {
                GameObject managerObj = new GameObject("[InfoPanelUI]");
                _instance = managerObj.AddComponent<InfoPanelUI>();
            }
        }
    }

    private void Awake()
    {
        if (_instance != null && _instance != this)
        {
            // If existing instance was auto-generated by AutoInitialize, replace it with this real scene UI instance configured in Editor!
            if (_instance.isAutoGenerated && !this.isAutoGenerated)
            {
                Destroy(_instance.gameObject);
                _instance = this;
                if (transform.parent == null) DontDestroyOnLoad(gameObject);
            }
            else if (_instance.panel == null && this.panel != null)
            {
                _instance.panel = this.panel;
                _instance.contentImage = this.contentImage;
                _instance.backgroundButton = this.backgroundButton;
                _instance.SetupButtonListener();
                Destroy(gameObject);
                return;
            }
            else
            {
                Destroy(gameObject);
                return;
            }
        }
        else
        {
            _instance = this;
            if (transform.parent == null) DontDestroyOnLoad(gameObject);
        }

        if (panel == null)
        {
            CreateDefaultInfoUI();
        }

        SetupButtonListener();

        if (panel != null)
        {
            panel.SetActive(false);
        }
    }

    private void SetupButtonListener()
    {
        if (backgroundButton != null)
        {
            backgroundButton.onClick.RemoveAllListeners();
            backgroundButton.onClick.AddListener(ClosePanel);
        }
    }

    private void Update()
    {
        if (panel == null || !panel.activeSelf) return;

        // Prevent closing on the exact same frame the panel was opened
        if (Time.frameCount == openedFrame) return;

        // Allow closing via Escape key
        if (IsEscapeKeyPressed())
        {
            ClosePanel();
            return;
        }

        // Check if user clicked mouse / screen
        if (IsPointerOrMouseClicked())
        {
            // If the click point is NOT on the center content image (i.e. clicked blank area), close panel
            if (!IsPointerOverContentImage())
            {
                ClosePanel();
            }
        }
    }

    private bool IsEscapeKeyPressed()
    {
#if ENABLE_LEGACY_INPUT_MANAGER
        if (Input.GetKeyDown(KeyCode.Escape)) return true;
#endif

#if ENABLE_INPUT_SYSTEM
        if (Keyboard.current != null && Keyboard.current.escapeKey.wasPressedThisFrame) return true;
#endif

        return false;
    }

    private bool IsPointerOrMouseClicked()
    {
#if ENABLE_LEGACY_INPUT_MANAGER
        if (Input.GetMouseButtonDown(0)) return true;
#endif

#if ENABLE_INPUT_SYSTEM
        if (Pointer.current != null && Pointer.current.press.wasPressedThisFrame) return true;
#endif
        return false;
    }

    private bool IsPointerOverContentImage()
    {
        if (contentImage == null) return false;

        Vector2 mousePos = Vector2.zero;

#if ENABLE_LEGACY_INPUT_MANAGER
        mousePos = Input.mousePosition;
#endif

#if ENABLE_INPUT_SYSTEM
        if (Pointer.current != null)
        {
            mousePos = Pointer.current.position.ReadValue();
        }
#endif

        return RectTransformUtility.RectangleContainsScreenPoint(contentImage.rectTransform, mousePos);
    }

    /// <summary>
    /// Displays the Info Panel with the provided sprite graphic.
    /// Disables player interaction and movement while open.
    /// Optionally accepts notification text to display via NotificationUI when panel is closed.
    /// </summary>
    public void ShowInfo(Sprite infoSprite, string notificationOnClose = "Something has changed within the map.")
    {
        pendingNotificationOnClose = notificationOnClose;

        if (!gameObject.activeSelf)
        {
            gameObject.SetActive(true);
        }

        if (panel == null)
        {
            CreateDefaultInfoUI();
        }

        SetupButtonListener();

        if (contentImage != null)
        {
            contentImage.sprite = infoSprite;
            contentImage.enabled = (infoSprite != null);
        }

        if (panel != null)
        {
            panel.SetActive(true);
        }

        openedFrame = Time.frameCount;

        // Lock player interaction & movement while info panel is active
        if (PlayerInteractor.Instance != null)
        {
            PlayerInteractor.Instance.SetInteractionEnabled(false);
        }

        if (PlayerController.Instance != null)
        {
            PlayerController.Instance.enabled = false;
            Rigidbody2D rb = PlayerController.Instance.GetComponent<Rigidbody2D>();
            if (rb != null)
            {
                rb.linearVelocity = Vector2.zero;
            }
        }
    }

    /// <summary>
    /// Closes the Info Panel and re-enables player interaction & movement.
    /// Triggers NotificationUI if a notification message was queued.
    /// </summary>
    public void ClosePanel()
    {
        if (AudioManager.Instance != null)
        {
            AudioManager.Instance.PlaySFX("button_click");
        }

        if (panel != null)
        {
            panel.SetActive(false);
        }

        // Re-enable player interaction & movement
        if (PlayerInteractor.Instance != null)
        {
            PlayerInteractor.Instance.SetInteractionEnabled(true);
        }

        if (PlayerController.Instance != null)
        {
            PlayerController.Instance.enabled = true;
        }

        // Show notification on panel close if pending
        if (!string.IsNullOrEmpty(pendingNotificationOnClose))
        {
            NotificationUI.ShowNotification(pendingNotificationOnClose);
            pendingNotificationOnClose = null;
        }
    }

    /// <summary>
    /// Auto-creates a clean default UI hierarchy if none is assigned in Scene / Inspector.
    /// </summary>
    private void CreateDefaultInfoUI()
    {
        isAutoGenerated = true;

        GameObject canvasObj = new GameObject("[InfoPanelCanvas]");
        canvasObj.transform.SetParent(transform);

        Canvas canvas = canvasObj.AddComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;
        canvas.sortingOrder = 900; // Below SceneFader (999), above general UI

        canvasObj.AddComponent<CanvasScaler>();
        canvasObj.AddComponent<GraphicRaycaster>();

        panel = new GameObject("InfoPanelContainer");
        panel.transform.SetParent(canvasObj.transform, false);

        RectTransform panelRect = panel.AddComponent<RectTransform>();
        panelRect.anchorMin = Vector2.zero;
        panelRect.anchorMax = Vector2.one;
        panelRect.sizeDelta = Vector2.zero;

        // Background overlay for click-to-close
        GameObject bgObj = new GameObject("BackgroundOverlay");
        bgObj.transform.SetParent(panel.transform, false);

        Image bgImage = bgObj.AddComponent<Image>();
        bgImage.color = new Color(0f, 0f, 0f, 0.65f); // Dark translucent background

        RectTransform bgRect = bgObj.GetComponent<RectTransform>();
        bgRect.anchorMin = Vector2.zero;
        bgRect.anchorMax = Vector2.one;
        bgRect.sizeDelta = Vector2.zero;

        backgroundButton = bgObj.AddComponent<Button>();
        SetupButtonListener();

        // Center Content Image container
        GameObject imgObj = new GameObject("CenterContentImage");
        imgObj.transform.SetParent(panel.transform, false);

        contentImage = imgObj.AddComponent<Image>();
        contentImage.preserveAspect = true;

        // Add EventTrigger to ContentImage so clicking directly on the image doesn't close panel
        EventTrigger trigger = imgObj.AddComponent<EventTrigger>();
        EventTrigger.Entry entry = new EventTrigger.Entry();
        entry.eventID = EventTriggerType.PointerClick;
        entry.callback.AddListener((data) => { /* Consume click event so background button is not triggered */ });
        trigger.triggers.Add(entry);

        RectTransform imgRect = imgObj.GetComponent<RectTransform>();
        imgRect.anchorMin = new Vector2(0.5f, 0.5f);
        imgRect.anchorMax = new Vector2(0.5f, 0.5f);
        imgRect.pivot = new Vector2(0.5f, 0.5f);
        imgRect.sizeDelta = new Vector2(600f, 600f);

        // Default guide text at bottom of screen (only used when UI is auto-generated)
        GameObject textObj = new GameObject("GuideText");
        textObj.transform.SetParent(panel.transform, false);

        TMP_Text defaultText = textObj.AddComponent<TextMeshProUGUI>();
        defaultText.text = "Click anywhere blank or press Esc to close";
        defaultText.fontSize = 24;
        defaultText.alignment = TextAlignmentOptions.Center;
        defaultText.color = Color.white;

        RectTransform textRect = textObj.GetComponent<RectTransform>();
        textRect.anchorMin = new Vector2(0.5f, 0.08f);
        textRect.anchorMax = new Vector2(0.5f, 0.08f);
        textRect.pivot = new Vector2(0.5f, 0.5f);
        textRect.sizeDelta = new Vector2(800f, 600f);
    }
}
